### PR TITLE
Update Rivals Mode

### PR DESCRIPTION
**Pull request by Samsung27**
Since I first made the Rivals mode, I've learned a bit more about Rivals and about how rectangle controllers work. Rivals mode desperately needed an update which fixed a couple bugs and added some features such as:
- Making sure all 48 DI angles, 24 Zetterburn Up B angles, and 16 Air Dodge angles were accounted for
- Removed unnecessary checks (angled fstrongs aren't a thing in rivals iirc) and other redundant left stick inputs
- Added in MS and LS as extra buttons too (Left stick click and Right stick click)
- Fixed bugs (can now crouch on plats with mod_y and pressing mod_x doesn't stop you from using ftilt)

It'll likely need more testing, but I figured I should drop the PR now since the old Rivals mode is missing important stuff like the angles and crouching on plats.

### CODE REVIEW

**Comment by JonnyHaystack** [comment]
Looks good to me. Thanks for this! 😄

**Comment by ScribeAwoken** [comment]
Just as a heads-up: Angled f-strongs and f-tilts _are_ a thing in Rivals... sort of. None of the official characters have them, but several Workshop characters do.

**Comment by Samsung27** [comment]
Ah, that's why angled f strongs were there. Thanks for letting me know! If you could direct me to a workshop char that needs those angles I can try and add the feature back in when I have time. That's my bad for forgetting about workshop. There are probably a lot of features that I am just not aware of that exist in workshop.

**Comment by ScribeAwoken** [comment]
Off the top of my head:

Exactly three workshop characters have angled f-tilts:
- [Bluey](https://steamcommunity.com/sharedfiles/filedetails/?id=1882960192)
- [Cinna](https://steamcommunity.com/sharedfiles/filedetails/?id=2014106219)
- [Mii Brawler](https://steamcommunity.com/sharedfiles/filedetails/?id=2034474077)

And at least one workshop character has an angled F-strong:
- [Retroblast](https://steamcommunity.com/sharedfiles/filedetails/?id=2687880389)

On top of that, among the official roster, Sylvanos can angle his bair.

**Comment by Samsung27** [comment]
Nice, thanks. I'll probably get started adding those back in tomorrow. You had me a bit scared that I broke Sylv bair when you mentioned him, but after making sure in-game really quick you can still angle it by pressing down/up + cstick left/right.

**Pull request merged**
